### PR TITLE
Kubernetes support

### PR DESCRIPTION
**Pull request by dpatel257**
Had to change 'kafka' to 'kafka-service' in order to be align with auto generation of K8S env variables which was causing kafka not to start.

### CODE REVIEW

**Comment by xwu2git** [comment]
Why do we need to auto-generate K8S from docker-compose? Can we have native K8S support scripts?

**Comment by dpatel257** [comment]
this is generating K8s scripts from a psuedo file named 'docker-compose-template.yml', which is maintained in the same folder. /deployment/kubernetes

**Comment by xwu2git** [comment]
Why include *.bak files? Why hard-code the pem file?

**Comment by dpatel257** [comment]
Generating certificate files on starting k8s now. Removed .bak files

**Comment by jhou5** [comment]
Pls. update README for how to use it

**Pull request merged**
